name: Trigger Netlify Build
on:
  push:
    paths:
      - 'images/**' # Only triggers when files in the "images" folder change

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Call Netlify Webhook
        run: |
          curl -X POST -d {} ${{ secrets.NETLIFY_BUILD_HOOK }}
